name: run-test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronoize]
    branches:
      - main

permissions:
  contents: read

jobs:
  # jsonファイルより、テスト対象の環境を読み込む
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Matrix
        id: set-matrix
        uses: "./.github/actions/load-yaml-file"
        with:
          file_path: "ci/run-test/env-matrix.yml"

  # testまでの一連の処理
  build-test:
    needs: load-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ninja (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake

      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew update && brew install ninja cmake

      - name: Install GCC for Linux
        if: runner.os == 'Linux' && matrix.kind == 'gcc'
        uses: "./.github/actions/install-gcc"
        with:
          version: ${{ matrix.version }}

      - name: Install Clang for Linux
        if: runner.os == 'Linux' && matrix.kind == 'clang'
        uses: "./.github/actions/install-clang"
        with:
          version: ${{ matrix.version }}

      # （任意）WindowsでCMakeが見つからないケースへの保険
      # 通常は runner でCMake/VSが入っているため不要なことが多いです。 :contentReference[oaicite:2]{index=2}
      # - name: Ensure CMake (Windows)
      #   if: runner.os == 'Windows'
      #   uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }}
